version: "3.9"
   
services:
  backend:
    image: tenshiro/nodejs-iig
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE=${DATABASE}
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}

  fontend:
    image: tenshiro/react-iig
    build: 
      context: .
      dockerfile: react.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API=${REACT_APP_API}